version: "3.8"

networks:
  traefik-proxy:
    external: true
  toby-beta:
    driver: bridge

volumes:
  toby-beta-pgsql-data:
    name: toby-beta-pgsql-data
  toby-beta-redis-data:
    name: toby-beta-redis-data
  toby-beta-static-assets:
    name: toby-beta-static-assets

services:
  toby-beta-web:
    image: nginx:1.23-alpine
    container_name: toby-beta-web
    volumes:
      - toby-beta-static-assets:/application/public
      - ./environment/prod/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.toby-beta-web.rule=Host(`${TOBY_HOST_NAME}`)"
      - "traefik.http.routers.toby-beta-web.entrypoints=websecure"
      - "traefik.http.routers.toby-beta-web.tls=true"
      - "traefik.http.routers.toby-web-beta.tls.certresolver=lets-encrypt-resolver"
    networks:
      - traefik-proxy
      - toby-beta
    restart: unless-stopped
    depends_on:
      - toby-beta-php
      - toby-beta-database

  toby-beta-php: &app
    build:
      context: .
      dockerfile: environment/prod/php/Dockerfile
      target: prod
    container_name: toby-beta-php
    working_dir: /application
    volumes:
      - toby-beta-static-assets:/application/public
      - ./environment/prod/php/php.ini:/usr/local/etc/php/conf.d/99-toby-php.ini
    networks:
      - toby-beta
    restart: unless-stopped

  toby-beta-worker:
    <<: *app
    container_name: toby-beta-worker
    volumes:
      - ./environment/prod/worker/php.ini:/usr/local/etc/php/conf.d/99-toby-php.ini
    user: root
    entrypoint: [ "./environment/prod/worker/entrypoint.sh" ]

  toby-beta-database:
    image: postgres:15
    container_name: toby-beta-database
    environment:
      - PGPASSWORD=${DOCKER_TOBY_BETA_DB_ROOT_PASSWORD}
      - POSTGRES_DB=${DOCKER_TOBY_BETA_DB_DATABASE}
      - POSTGRES_USER=${DOCKER_TOBY_BETA_DB_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_TOBY_BETA_DB_PASSWORD}
    volumes:
      - toby-beta-pgsql-data:/var/lib/postgresql/data
    ports:
      - "7777:5432"
    networks:
      - toby-beta
    restart: unless-stopped

  toby-beta-redis:
    image: redis:7.0-alpine3.16
    container_name: toby-beta-redis
    volumes:
      - toby-beta-redis-data:/data
    networks:
      - toby-beta
    restart: unless-stopped
