version: "3.8"

networks:
  traefik-proxy:
    external: true
  toby-beta:
    driver: bridge

volumes:
  toby-beta-pgsql-data:
    name: toby-beta-pgsql-data
  toby-beta-redis-data:
    name: toby-beta-redis-data
  toby-beta-static-assets:
    name: toby-beta-static-assets
  duplicati-source:
    name: duplicati-source
    external: true

# extension fields
x-toby-app-shared: &app
  image: toby-beta-app:latest
  container_name: toby-beta-php
  working_dir: /application
  volumes:
    - duplicati-source:/backup
    - toby-beta-static-assets:/application/public
    - ./environment/prod/php/php.ini:/usr/local/etc/php/conf.d/99-toby-php.ini
    - ./.env:/application/.env
  networks:
    - toby-beta
  restart: unless-stopped

services:
  toby-beta-web:
    image: nginx:1.23-alpine
    container_name: toby-beta-web
    volumes:
      - toby-beta-static-assets:/application/public
      - ./environment/prod/nginx/templates:/etc/nginx/templates/
    environment:
      - SERVER_NAME=toby-beta-nginx
      - FASTCGI_PASS_NAME=toby-beta-php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.toby-beta-web.rule=Host(`${TOBY_HOST_NAME:? variable TOBY_HOST_NAME not set}`)"
      - "traefik.http.routers.toby-beta-web.entrypoints=websecure"
      - "traefik.http.routers.toby-beta-web.tls=true"
      - "traefik.http.routers.toby-beta-web.tls.certresolver=lets-encrypt-resolver"
      - "traefik.http.routers.toby-beta-web.middlewares=response-gzip-compress@file"
    networks:
      - traefik-proxy
      - toby-beta
    restart: unless-stopped
    depends_on:
      - toby-beta-php
      - toby-beta-database

  toby-beta-php:
    build:
      context: .
      dockerfile: environment/prod/php/Dockerfile
      target: prod
    <<: *app

  toby-beta-worker:
    <<: *app
    container_name: toby-beta-worker
    volumes:
      - ./environment/prod/worker/php.ini:/usr/local/etc/php/conf.d/99-worker-toby-php.ini
      - ./.env:/application/.env
    user: root
    entrypoint: [ "./environment/prod/worker/entrypoint.sh" ]

  toby-beta-scheduler:
    <<: *app
    container_name: toby-beta-scheduler
    volumes:
      - ./environment/prod/scheduler/php.ini:/usr/local/etc/php/conf.d/99-scheduler-toby-php.ini
      - ./.env:/application/.env
    user: root
    entrypoint: [ "./environment/prod/scheduler/entrypoint.sh" ]

  toby-beta-database:
    image: postgres:15
    container_name: toby-beta-database
    environment:
      - PGPASSWORD=${DOCKER_TOBY_BETA_DB_ROOT_PASSWORD:? variable DOCKER_TOBY_BETA_DB_ROOT_PASSWORD not set}
      - POSTGRES_DB=${DOCKER_TOBY_BETA_DB_DATABASE:? variable DOCKER_TOBY_BETA_DB_DATABASE not set}
      - POSTGRES_USER=${DOCKER_TOBY_BETA_DB_USERNAME:? variable DOCKER_TOBY_BETA_DB_USERNAME not set}
      - POSTGRES_PASSWORD=${DOCKER_TOBY_BETA_DB_PASSWORD:? variable DOCKER_TOBY_BETA_DB_PASSWORD not set}
    volumes:
      - toby-beta-pgsql-data:/var/lib/postgresql/data
    networks:
      - toby-beta
    restart: unless-stopped

  toby-beta-redis:
    image: redis:7.0-alpine3.16
    container_name: toby-beta-redis
    volumes:
      - toby-beta-redis-data:/data
    networks:
      - toby-beta
    restart: unless-stopped
